### ISSUE TITLE
Enable Firmware Build outside of IDE

### ISSUE THREAD

**Issue by mrshake** [brewtrollergit/brewtroller#2]
Enable Firmware Build outside of IDE

**Comment by ericyanush** [comment]
1. Commit 70dc7f0 adds support/now requires building with CMake
2. Compiler warnings from old code were fixed with branch merge in commit 0ea8d94
3. Compiler/linker optimizations were merged with commit 45e8a0e (Resulting in approximately 5K compiled binary space savings)

**Comment by mrshake** [comment]
Nice dude!!!
